const SUPABASE_URL="https://hkakedonludcqjgjzkei.supabase.co";
const SUPABASE_KEY="sb_publishable_AQWeYHI3Xli_1iBKVr9EPg_8L8PR-Hc";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let CHARIOTS=[],USER=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtCap=v=>{let s=String(v??'').trim().toUpperCase().replace(/\s*T$/,'');return s?s+' T':'—'};
function nav(){const page=location.pathname.split('/').pop()||'dashboard.html';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===page));}
function toggleMenu(){document.querySelector('.overlay')?.classList.toggle('open')}
function shell(){nav();document.querySelector('.overlay')?.addEventListener('click',e=>{if(e.target.classList.contains('overlay'))toggleMenu()})}
async function session(requireLogin=true){const {data}=await sb.auth.getSession();USER=data.session?.user||null;if(!USER&&requireLogin){location.href='index.html';return false}return true}
async function login(){const email=$('#email').value.trim(),password=$('#password').value,msg=$('#msg');msg.textContent='Connexion...';const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return}try{const {data:s}=await sb.rpc('get_my_sbi_status');if(s?.disabled){await sb.auth.signOut();msg.textContent='Compte désactivé.';return}}catch{}location.href='dashboard.html'}
async function logout(){await sb.auth.signOut();location.href='index.html'}
async function load(){const {data,error}=await sb.from('chariots').select('*').order('id',{ascending:false});if(error)throw error;CHARIOTS=data||[];return CHARIOTS}
function badge(c){const s=String(c.status||'').toLowerCase();return s.includes('livr')?'badge':s.includes('prépar')||s.includes('fabric')?'badge orange':s.includes('bloqu')?'badge red':'badge'}
function card(c){return `<div class="item" onclick="location.href='chariot.html?id=${encodeURIComponent(c.qr_id||'')}'"><div class="item-main"><div class="item-title">${esc(c.qr_id)}</div><div class="meta">${esc(c.chassis)} • ${esc(c.engine)} • ${fmtCap(c.capacity)}${c.client?' • '+esc(c.client):''}</div></div><span class="${badge(c)}">${esc(c.status||c.stock||'En stock')}</span></div>`}
function isDelivered(c){return /livr/i.test(String(c.status||''))||!!c.delivery_date}
function isStock(c){return !isDelivered(c)&&!/(fabric)/i.test(String(c.stock||c.status||''))}
async function dashboard(){if(!await session())return;await load();$('#total').textContent=CHARIOTS.length;$('#stock').textContent=CHARIOTS.filter(isStock).length;$('#fab').textContent=CHARIOTS.filter(c=>/fabric/i.test(String(c.stock||c.status||''))).length;$('#delivered').textContent=CHARIOTS.filter(isDelivered).length;const rows=[...CHARIOTS].sort((a,b)=>new Date(b.updated_at||0)-new Date(a.updated_at||0)).slice(0,6);$('#recent').innerHTML=rows.map(c=>card(c)).join('')||'<div class="empty">Aucun chariot.</div>'}
async function listPage(mode='all'){if(!await session())return;await load();const input=$('#search');const render=()=>{let rows=CHARIOTS;if(mode==='stock')rows=rows.filter(isStock);if(mode==='delivered')rows=rows.filter(isDelivered);const q=input?.value.trim().toLowerCase();if(q)rows=rows.filter(c=>[c.qr_id,c.chassis,c.engine,c.client,c.capacity].some(v=>String(v||'').toLowerCase().includes(q)));$('#list').innerHTML=rows.map(card).join('')||'<div class="empty">Aucun résultat.</div>'};input?.addEventListener('input',render);render()}
async function detail(){if(!await session())return;await load();const id=new URLSearchParams(location.search).get('id');const c=CHARIOTS.find(x=>String(x.qr_id)===String(id));if(!c){$('#detail').innerHTML='<div class="empty">Chariot introuvable.</div>';return}$('#title').textContent=c.qr_id||'Chariot';$('#status').textContent=c.status||c.stock||'—';const groups=[['Identification',[['N° châssis',c.chassis],['N° série',c.serial_number],['N° moteur',c.engine_number],['Moteur',c.engine]]],['Caractéristiques',[['Capacité',fmtCap(c.capacity)],['Hauteur',c.lifting_height],['Mât',c.mast_type],['Pneus',c.tire_type],['Couleur',c.color]]],['Informations stock',[['Stock',c.stock],['Statut',c.status],['Client',c.client],['Date livraison',c.delivery_date]]],['Observations',[['Observations',c.observations]]]];$('#detail').innerHTML=groups.map(g=>`<div class="section"><h3>${g[0]}</h3><div class="details">${g[1].map(x=>`<div class="kv"><small>${x[0]}</small><b>${esc(x[1]||'—')}</b></div>`).join('')}</div></div>`).join('');$('#edit').onclick=()=>location.href='nouveau-chariot.html?id='+encodeURIComponent(c.qr_id)}
function norm(s){return String(s||'').trim().toUpperCase().replace(/\s+/g,' ')}
async function newPage(){if(!await session())return;await load();const id=new URLSearchParams(location.search).get('id');const old=CHARIOTS.find(c=>String(c.qr_id)===String(id));if(old){$('#formTitle').textContent='Modifier '+old.qr_id;for(const [k,v] of Object.entries(old)){const el=document.querySelector(`[name="${k}"]`);if(el)el.value=v??''}}else{$('[name="qr_id"]').value=nextQr()}}
function nextQr(){let n=Math.max(0,...CHARIOTS.map(c=>Number(String(c.qr_id||'').match(/(\d+)$/)?.[1]||0)))+1;return 'CH-'+String(n).padStart(4,'0')}
async function saveChariot(){const f=$('#chariotForm'),fd=new FormData(f),p=Object.fromEntries(fd.entries());if(!p.chassis||!p.engine||!p.capacity){alert('N° châssis, moteur et capacité sont obligatoires.');return}const oldId=new URLSearchParams(location.search).get('id');const duplicate=CHARIOTS.find(c=>norm(c.chassis)===norm(p.chassis)&&norm(c.engine)===norm(p.engine)&&String(c.qr_id)!==String(oldId));if(duplicate){alert(`Le châssis ${p.chassis} existe déjà avec le même moteur ${p.engine} (${duplicate.qr_id}).`);return}p.updated_at=new Date().toISOString();const {error}=oldId?await sb.from('chariots').update(p).eq('qr_id',oldId):await sb.from('chariots').insert(p);if(error){alert(error.message);return}location.href='chariot.html?id='+encodeURIComponent(p.qr_id)}
async function qrPage(){if(!await session())return;await load();const sel=$('#qrSelect');CHARIOTS.forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${esc(c.qr_id)}">${esc(c.qr_id)} — ${esc(c.chassis)} — ${esc(c.engine)} — ${fmtCap(c.capacity)}</option>`));sel.onchange=()=>renderQR(sel.value);if(CHARIOTS[0]){sel.value=CHARIOTS[0].qr_id;renderQR(sel.value)}}
function renderQR(id){const box=$('#qr');box.innerHTML='';if(!id)return;new QRCode(box,{text:location.origin+location.pathname.replace('qr-codes.html','chariot.html')+'?id='+encodeURIComponent(id),width:220,height:220});$('#qrLabel').textContent=id}
async function historyPage(){if(!await session())return;await load();const rows=[...CHARIOTS].sort((a,b)=>new Date(b.updated_at||0)-new Date(a.updated_at||0));$('#historyList').innerHTML=rows.map(c=>`<div class="item" onclick="location.href='chariot.html?id=${encodeURIComponent(c.qr_id)}'"><div class="item-main"><div class="item-title">${esc(c.qr_id)} — ${esc(c.chassis)}</div><div class="meta">Dernière mise à jour : ${c.updated_at?new Date(c.updated_at).toLocaleString('fr-FR'):'—'} • ${esc(c.engine)} • ${fmtCap(c.capacity)}</div></div></div>`).join('')}
document.addEventListener('DOMContentLoaded',shell);
