/* SBI SAV / retours clients — isolated module; does not alter the normal chariot workflow. */
async function retoursClientsPage(){
  if(!(await session()))return;
  await loadChariots();
  const BUCKET='sbi-retours-clients';
  const $r=id=>document.getElementById(id);
  const fields={
    search:$r('returnSearch'),statusFilter:$r('returnStatusFilter'),from:$r('returnFrom'),to:$r('returnTo'),reset:$r('returnReset'),
    total:$r('returnTotal'),repair:$r('returnRepair'),waiting:$r('returnWaiting'),ready:$r('returnReady'),count:$r('returnCount'),cases:$r('returnCases'),
    newBtn:$r('newReturnBtn'),formCard:$r('returnFormCard'),form:$r('returnForm'),formTitle:$r('returnFormTitle'),formError:$r('returnFormError'),formNotice:$r('returnFormNotice'),
    cancel:$r('cancelReturnForm'),clear:$r('resetReturnForm'),save:$r('saveReturnBtn'),globalNotice:$r('returnGlobalNotice'),
    chariotSearch:$r('returnChariotSearch'),chariotResults:$r('returnChariotResults'),selectedChariot:$r('returnChariot'),client:$r('returnClient'),date:$r('returnDate'),category:$r('returnCategory'),condition:$r('returnCondition'),status:$r('returnStatus'),problem:$r('returnProblem'),diagnosis:$r('returnDiagnosis'),repairAction:$r('returnRepairAction'),parts:$r('returnParts'),technician:$r('returnTechnician'),decision:$r('returnDecision'),restitutedDate:$r('returnRestitutedDate'),observations:$r('returnObservations'),images:$r('returnImages'),imagesPreview:$r('returnImagesPreview')
  };
  let rows=[],editingId=null,selectedMachine=null,pendingFiles=[],objectUrls=[],viewCaseId=null;
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const caseStatusDone=s=>['Restitué au client','Clôturé sans réparation'].includes(String(s||''));
  const statusClass=s=>s==='Réparé / prêt à restituer'||s==='Restitué au client'?'is-done':s==='Clôturé sans réparation'?'is-closed':s==='Retour signalé'||s==='En attente diagnostic'?'':'is-active';
  const mapDbCase=row=>({caseId:String(row.case_id||''),qrId:String(row.qr_id||''),chassis:String(row.chassis||''),engine:String(row.engine||''),capacity:String(row.capacity||''),stock:String(row.stock||''),client:String(row.client||''),returnDate:String(row.return_date||''),category:String(row.category||''),condition:String(row.return_condition||''),status:String(row.status||'Retour signalé'),problem:String(row.problem||''),diagnosis:String(row.diagnosis||''),repairAction:String(row.repair_action||''),parts:String(row.parts||''),technician:String(row.technician||''),decision:String(row.decision||''),restitutedDate:String(row.restituted_date||''),observations:String(row.observations||''),images:Array.isArray(row.images)?row.images:[],history:Array.isArray(row.history)?row.history:[],createdBy:row.created_by||null,updatedBy:row.updated_by||null,createdAt:row.created_at||'',updatedAt:row.updated_at||''});
  function showMsg(el,msg,kind='success'){if(!el)return;el.textContent=msg;el.classList.add('show');if(kind==='error'){el.classList.remove('return-notice');el.classList.add('return-error')}else{el.classList.remove('return-error');el.classList.add('return-notice')}}
  function hideMsg(el){if(!el)return;el.classList.remove('show');el.textContent=''}
  function fillStatusFilter(){const old=fields.statusFilter.value;const all=[...new Set(rows.map(x=>x.status).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));fields.statusFilter.innerHTML='<option value="">Tous les statuts</option>'+all.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(all.includes(old))fields.statusFilter.value=old}
  async function loadCases(){
    fields.cases.innerHTML='<div class="return-empty">Chargement des dossiers SAV…</div>';
    const result=await withTimeout(supabaseClient.from('sbi_sav_returns').select('*').order('return_date',{ascending:false}).limit(1000),12000);
    if(result.error)throw result.error;
    rows=(result.data||[]).map(mapDbCase).filter(x=>x.caseId).sort((a,b)=>String(b.returnDate||'').localeCompare(String(a.returnDate||''))||String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));
    fillStatusFilter();render();
  }
  function searchText(item){return norm([item.chassis,item.qrId,item.client,item.engine,item.capacity,item.category,item.problem,item.diagnosis,item.repairAction,item.parts,item.technician,item.decision,item.observations,item.status,item.stock].join(' '))}
  function filtered(){const q=norm(fields.search.value||''),from=fields.from.value,to=fields.to.value,status=fields.statusFilter.value;return rows.filter(x=>(!q||searchText(x).includes(q))&&(!status||x.status===status)&&(!from||String(x.returnDate||'')>=from)&&(!to||String(x.returnDate||'')<=to))}
  function updateStats(){fields.total.textContent=rows.filter(x=>!caseStatusDone(x.status)).length;fields.repair.textContent=rows.filter(x=>x.status==='Réparation en cours').length;fields.waiting.textContent=rows.filter(x=>x.status==='En attente de pièces').length;fields.ready.textContent=rows.filter(x=>['Réparé / prêt à restituer','Restitué au client'].includes(x.status)).length}
  function render(){updateStats();const list=filtered();fields.count.textContent=`${list.length} dossier${list.length===1?'':'s'} affiché${list.length===1?'':'s'} sur ${rows.length}`;fields.cases.innerHTML=list.length?list.map(x=>{
    const photos=Array.isArray(x.images)?x.images.length:0;
    const details=[['Date du retour',x.returnDate],['Type de problème',x.category],['État à réception',x.condition],['Technicien',x.technician],['Décision finale',x.decision],['Date de restitution',x.restitutedDate]].filter(([k,v])=>v);
    return `<article class="return-case" data-case="${esc(x.caseId)}"><div class="return-case-head"><div><div class="return-case-title">${esc(x.chassis||x.qrId||'Chariot')} — ${esc(x.client||'Client non renseigné')}</div><div class="return-case-sub">${esc(x.engine||'Moteur —')} · ${esc(x.capacity||'Capacité —')} · ${esc(x.stock||'Emplacement —')}</div></div><span class="return-status ${statusClass(x.status)}">${esc(x.status||'Retour signalé')}</span></div><div class="return-case-details">${details.map(([k,v])=>`<div class="return-detail"><div class="return-detail-label">${esc(k)}</div><div class="return-detail-value">${esc(v)}</div></div>`).join('')}</div><div class="return-case-notes"><strong>Problème :</strong> ${esc(x.problem||'—')}</div>${x.diagnosis?`<div class="return-case-notes"><strong>Diagnostic :</strong> ${esc(x.diagnosis)}</div>`:''}${x.repairAction?`<div class="return-case-notes"><strong>Réparation :</strong> ${esc(x.repairAction)}</div>`:''}${x.parts?`<div class="return-case-notes"><strong>Pièces :</strong> ${esc(x.parts)}</div>`:''}${x.observations?`<div class="return-case-notes"><strong>Observations :</strong> ${esc(x.observations)}</div>`:''}${x.history?.length?`<details class="return-case-history"><summary>Historique du dossier (${x.history.length})</summary><div class="return-history-list">${[...x.history].reverse().map(h=>`<div class="return-history-item"><strong>${esc(h.action||'Mise à jour')}</strong><span>${esc(h.detail||h.status||'')}</span><small>${esc(h.at?new Date(h.at).toLocaleString('fr-FR'):'—')} · ${esc(h.user||'Utilisateur')}</small></div>`).join('')}</div></details>`:''}<div class="return-case-actions"><button class="btn light" type="button" data-edit-return="${esc(x.caseId)}">Modifier / suivi</button>${photos?`<button class="btn light" type="button" data-view-photos="${esc(x.caseId)}">📷 Photos (${photos})</button>`:''}<a class="btn light" href="chariot.html?id=${encodeURIComponent(x.qrId||'')}">Fiche du chariot</a></div></article>`;
  }).join(''):'<div class="return-empty">Aucun dossier ne correspond à la recherche.</div>'}
  function cleanObjectUrls(){objectUrls.forEach(u=>{try{URL.revokeObjectURL(u)}catch(_){}});objectUrls=[]}
  function clearPhotoPreview(){cleanObjectUrls();pendingFiles=[];fields.images.value='';fields.imagesPreview.innerHTML=''}
  function renderPendingPhotos(){cleanObjectUrls();fields.imagesPreview.innerHTML='';pendingFiles.forEach((file,index)=>{const url=URL.createObjectURL(file);objectUrls.push(url);const tile=document.createElement('div');tile.className='return-image-tile';tile.innerHTML=`<img src="${url}" alt="Aperçu photo ${index+1}"><div class="return-image-caption">${esc(file.name)}</div><button type="button" class="return-image-remove" data-remove-photo="${index}">Retirer</button>`;fields.imagesPreview.appendChild(tile)})}
  function clearForm(){fields.form.reset();editingId=null;selectedMachine=null;fields.save.textContent='Enregistrer le dossier';fields.selectedChariot.value='';fields.chariotSearch.value='';fields.chariotResults.innerHTML='';fields.chariotResults.hidden=true;clearPhotoPreview();fields.formTitle.textContent='Nouveau retour client';fields.save.textContent='Enregistrer le dossier';hideMsg(fields.formError);hideMsg(fields.formNotice)}
  function openForm(item=null){hideMsg(fields.formError);hideMsg(fields.formNotice);fields.formCard.hidden=false;editingId=item?.caseId||null;selectedMachine=null;fields.selectedChariot.innerHTML='<option value="">Sélectionner un chariot…</option>';fields.chariotSearch.value='';fields.chariotResults.innerHTML='';fields.chariotResults.hidden=true;clearPhotoPreview();
    fields.formTitle.textContent=item?'Modifier le dossier SAV':'Nouveau retour client';fields.save.textContent=item?'Enregistrer les modifications':'Enregistrer le dossier';
    fields.client.value=item?.client||'';fields.date.value=item?.returnDate||today();fields.category.value=item?.category||'';fields.condition.value=item?.condition||'';fields.status.value=item?.status||'Retour signalé';fields.problem.value=item?.problem||'';fields.diagnosis.value=item?.diagnosis||'';fields.repairAction.value=item?.repairAction||'';fields.parts.value=item?.parts||'';fields.technician.value=item?.technician||getUserDisplayName();fields.decision.value=item?.decision||'';fields.restitutedDate.value=item?.restitutedDate||'';fields.observations.value=item?.observations||'';
    if(item){const c=CHARIOTS.find(c=>String(c.qr_id)===String(item.qrId));if(c)selectMachine(c);else{fields.selectedChariot.innerHTML=`<option value="${esc(item.qrId||'')}">${esc(item.chassis||item.qrId||'Chariot')} — chariot non présent dans la liste actuelle</option>`;fields.selectedChariot.value=item.qrId||'';selectedMachine={qr_id:item.qrId,chassis:item.chassis,client:item.client,engine:item.engine,capacity:item.capacity,stock:item.stock};}}
    if(item?.images?.length)fields.imagesPreview.innerHTML=`<div class="return-image-help-empty">${item.images.length} photo(s) déjà enregistrée(s). Les nouvelles photos seront ajoutées.</div>`;
    fields.formCard.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>fields.chariotSearch.focus(),80);
  }
  function selectMachine(c){selectedMachine=c;fields.selectedChariot.innerHTML=`<option value="${esc(c.qr_id||'')}">${esc(c.chassis||c.qr_id||'Chariot')} — ${esc(c.engine||'Moteur —')} — ${esc(c.client||'Sans client')}</option>`;fields.selectedChariot.value=c.qr_id||'';if(c.client&&!fields.client.value)fields.client.value=c.client;fields.chariotSearch.value=c.chassis||c.qr_id||'';fields.chariotResults.hidden=true;fields.chariotResults.innerHTML=''}
  function searchMachines(){const q=norm(fields.chariotSearch.value||'');if(!q){fields.chariotResults.hidden=true;fields.chariotResults.innerHTML='';return}const hits=CHARIOTS.filter(c=>norm([c.chassis,c.qr_id,c.serial_number,c.engine_number,c.engine,c.client,c.capacity,c.stock,c.status].join(' ')).includes(q)).slice(0,30);fields.chariotResults.innerHTML=hits.length?hits.map(c=>`<button type="button" class="return-chariot-result" role="option" data-select-machine="${esc(c.qr_id||'')}"><strong>${esc(c.chassis||c.qr_id||'Chariot')}</strong><span>${esc(c.engine||'Moteur —')} · ${esc(c.capacity||'Capacité —')} · ${esc(c.client||'Sans client')} · ${esc(c.stock||'Emplacement —')}</span></button>`).join(''):'<div class="return-image-help-empty">Aucun chariot correspondant.</div>';fields.chariotResults.hidden=false}
  async function uploadPhotos(caseId,files){const list=[];try{for(const file of files){const ext=(String(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,8)||'jpg');const path=`${caseId}/${Date.now()}-${Math.random().toString(36).slice(2,8)}.${ext}`;const result=await supabaseClient.storage.from(BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||'image/jpeg'});if(result.error)throw result.error;list.push({path,name:file.name||path,contentType:file.type||''})}return list}catch(err){if(list.length){try{await supabaseClient.storage.from(BUCKET).remove(list.map(x=>x.path))}catch(_){}}throw err}}
  async function saveCase(e){e.preventDefault();hideMsg(fields.formError);hideMsg(fields.formNotice);const qr=fields.selectedChariot.value;if(!qr){showMsg(fields.formError,'Sélectionne un chariot dans les résultats de recherche.','error');fields.chariotSearch.focus();return}if(!fields.client.value.trim()){showMsg(fields.formError,'Le nom du client est obligatoire.','error');fields.client.focus();return}if(!fields.date.value||!fields.category.value||!fields.problem.value.trim()){showMsg(fields.formError,'Renseigne la date du retour, le type de problème et sa description.','error');return}if(pendingFiles.some(f=>!String(f.type||'').startsWith('image/'))){showMsg(fields.formError,'Seules les images sont acceptées.','error');return}if(pendingFiles.some(f=>f.size>10*1024*1024)){showMsg(fields.formError,'Chaque image doit peser 10 Mo maximum.','error');return}
    const wasEditing=!!editingId;const base=rows.find(x=>x.caseId===editingId)||null;const caseId=editingId||((window.crypto?.randomUUID?.())||('sav_'+Date.now()+'_'+Math.random().toString(36).slice(2,10)));let uploaded=[],saved=false;fields.save.disabled=true;fields.save.textContent='Enregistrement…';
    try{
      const newPhotos=pendingFiles.length?await uploadPhotos(caseId,pendingFiles):[];uploaded=newPhotos;
      const c=selectedMachine||CHARIOTS.find(x=>String(x.qr_id)===String(qr))||{};const now=new Date().toISOString();
      const payload={case_id:caseId,qr_id:String(qr),chassis:c.chassis||base?.chassis||'',engine:c.engine||base?.engine||'',capacity:c.capacity||base?.capacity||'',stock:c.stock||base?.stock||'',client:fields.client.value.trim(),return_date:fields.date.value,category:fields.category.value,return_condition:fields.condition.value||null,status:fields.status.value,problem:fields.problem.value.trim(),diagnosis:fields.diagnosis.value.trim()||null,repair_action:fields.repairAction.value.trim()||null,parts:fields.parts.value.trim()||null,technician:fields.technician.value.trim()||getUserDisplayName(),decision:fields.decision.value||null,restituted_date:fields.restitutedDate.value||null,observations:fields.observations.value.trim()||null,images:[...(base?.images||[]),...newPhotos],created_by:base?.createdBy||currentUser?.id||null,updated_by:currentUser?.id||null,created_at:base?.createdAt||now,updated_at:now};
      const oldStatus=base?.status||'';const detail=base?(oldStatus!==payload.status?`Statut : ${oldStatus||'—'} → ${payload.status}`:'Informations du dossier mises à jour'):`Dossier créé — statut : ${payload.status}`;
      payload.history=[...(base?.history||[]),{at:now,user:getUserDisplayName(),action:wasEditing?'Mise à jour du dossier':'Création du dossier',status:payload.status,detail}];
      const query=base?supabaseClient.from('sbi_sav_returns').update(payload).eq('case_id',caseId):supabaseClient.from('sbi_sav_returns').insert(payload);
      const result=await withTimeout(query,15000);
      if(result.error)throw result.error;
      saved=true;clearForm();fields.formCard.hidden=true;showMsg(fields.globalNotice,wasEditing?'Dossier SAV mis à jour.':'Dossier SAV créé.');
      try{await loadCases()}catch(refreshErr){showMsg(fields.globalNotice,'Dossier enregistré, mais la liste n’a pas pu être actualisée. Recharge la page.','success');console.warn('Actualisation de la liste SAV impossible',refreshErr)}
      fields.globalNotice.scrollIntoView({behavior:'smooth',block:'nearest'});
    }catch(err){
      if(!saved&&uploaded.length){try{await supabaseClient.storage.from(BUCKET).remove(uploaded.map(x=>x.path))}catch(_){}}
      let message=friendlySupabaseError(err);if(/bucket not found|not found/i.test(message))message+=' — Configure le bucket de photos en exécutant SUPABASE_SAV_RETURNS_SETUP.sql dans Supabase.';else if(/row.level security|permission denied|not allowed/i.test(message))message+=' — Exécute SUPABASE_SAV_RETURNS_SETUP.sql dans Supabase pour autoriser uniquement les dossiers SAV.';showMsg(fields.formError,'Enregistrement impossible : '+message,'error');
    }finally{fields.save.disabled=false;fields.save.textContent=editingId?'Enregistrer les modifications':'Enregistrer le dossier'}
  }
  async function showPhotos(id){const item=rows.find(x=>x.caseId===id);if(!item||!item.images?.length){alert('Aucune photo enregistrée.');return}const modal=$r('returnPhotoModal'),body=$r('returnPhotoModalBody');body.innerHTML='<div class="return-empty">Chargement des photos…</div>';modal.hidden=false;try{const html=[];for(const image of item.images){const {data,error}=await supabaseClient.storage.from(BUCKET).createSignedUrl(image.path,3600);if(error)throw error;html.push(`<a class="return-photo-modal-item" href="${esc(data.signedUrl)}" target="_blank" rel="noopener"><img src="${esc(data.signedUrl)}" alt="${esc(image.name||'Photo du retour')}"><span>${esc(image.name||'Photo')}</span></a>`)}body.innerHTML=html.join('')}catch(e){body.innerHTML=`<div class="return-empty">Impossible d’ouvrir les photos : ${esc(friendlySupabaseError(e))}. Vérifie les règles de stockage Supabase.</div>`}}
  fields.newBtn.addEventListener('click',()=>openForm());fields.cancel.addEventListener('click',()=>{clearForm();fields.formCard.hidden=true});fields.clear.addEventListener('click',()=>clearForm());fields.form.addEventListener('submit',saveCase);
  fields.search.addEventListener('input',render);[fields.statusFilter,fields.from,fields.to].forEach(x=>x.addEventListener('change',render));fields.reset.addEventListener('click',()=>{fields.search.value='';fields.statusFilter.value='';fields.from.value='';fields.to.value='';render()});
  fields.chariotSearch.addEventListener('input',searchMachines);fields.chariotSearch.addEventListener('focus',searchMachines);fields.chariotResults.addEventListener('click',e=>{const btn=e.target.closest('[data-select-machine]');if(!btn)return;const c=CHARIOTS.find(x=>String(x.qr_id)===String(btn.dataset.selectMachine));if(c)selectMachine(c)});
  fields.images.addEventListener('change',()=>{const files=Array.from(fields.images.files||[]);if(files.length>8){fields.images.value='';showMsg(fields.formError,'Maximum 8 photos par enregistrement.','error');return}pendingFiles=files;renderPendingPhotos()});fields.imagesPreview.addEventListener('click',e=>{const btn=e.target.closest('[data-remove-photo]');if(!btn)return;pendingFiles.splice(Number(btn.dataset.removePhoto),1);const dt=new DataTransfer();pendingFiles.forEach(f=>dt.items.add(f));fields.images.files=dt.files;renderPendingPhotos()});
  fields.cases.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-return]');if(edit){const item=rows.find(x=>x.caseId===edit.dataset.editReturn);if(item)openForm(item);return}const photos=e.target.closest('[data-view-photos]');if(photos)showPhotos(photos.dataset.viewPhotos)});
  $r('returnPhotoModalClose').addEventListener('click',()=>{$r('returnPhotoModal').hidden=true;$r('returnPhotoModalBody').innerHTML=''});$r('returnPhotoModal').addEventListener('click',e=>{if(e.target===$r('returnPhotoModal')){$r('returnPhotoModal').hidden=true;$r('returnPhotoModalBody').innerHTML=''}});
  try{await loadCases()}catch(e){fields.count.textContent='Impossible de charger les dossiers SAV';fields.cases.innerHTML=`<div class="return-empty">Erreur de lecture Supabase : ${esc(friendlySupabaseError(e))}. Vérifie la connexion et les politiques RLS.</div>`}
}
